#!/usr/bin/env bash

# :author:      Jeffrey Serio <hyperreal64@pm.me>
# :date:        17 Aug 2020
# :version:     0.0.1
#
# This script automates system auditing with lynis.
# It converts the output to html via ansi2html, saves 
# the file to _report_dir, and then sends a notifcation
# to Discord via webhook.
# TODO:
#
# Changelog:

set -euo pipefail

_date_stamp=$(date +'%m-%d-%Y')
_report_dir="/path/to/lynis-reports"
_audit_msg_ok="lynis audit for $(uname -n) ran successfully"
_audit_msg_fail="lynis audit for $(uname -n) failed"
_webhook_msg=${_webhook_msg:-$_audit_msg_ok}
_webhook_url="enter webhook url"

if ! [[ $(command -v lynis) ]]; then
  echo "lynis command not found"
  exit 1
fi

if ! [[ $(command -v discord-webhook.py) ]]; then
  echo "discord-webhook.py not found"
  exit 1
fi

if ! [[ $(command -v ansi2html) ]]; then
  echo "ansi2html not found"
  exit 1
fi

mkdir -p "${_report_dir}/${_date_stamp}"
sudo lynis audit system --logfile /var/log/lynis | ansi2html -a > "${_report_dir}/${_date_stamp}/${_date_stamp}-lynis-report.html" || _webhook_msg=${_audit_msg_fail}
discord-webhook.py -i "${_webhook_msg}" -u "${_webhook_url}"


# vim: set filetype=bash


