#!/usr/bin/env bash

set -euo pipefail

declare SNAPS=(
  gosec
)

echo "Installing SNAPS..."
sudo snap install "${SNAPS[@]}"

echo "Creating symlink from /snap to /var/lib/snapd/snap"
sudo ln -sf /var/lib/snapd/snap /snap

echo "Process complete!"
