#!/usr/bin/env bash

set -euo pipefail

declare BREW_PACKAGES=(
    bat 
    bitwarden-cli 
    chezmoi 
    fzf 
    golang 
    lsd 
    neovim 
    starship 
    topgrade
)

echo "Installing Linux brew packages..."
brew install "${BREW_PACKAGES[@]}"
echo "Done!"