#!/usr/bin/env bash

set -euo pipefail

_ulauncher_rpm_url=$(curl -s https://api.github.com/repos/Ulauncher/Ulauncher/releases/latest | grep "browser_download_url.*fedora32.rpm" | cut -d : -f 2,3 | tr -d \" | cut -d " " -f 1 --complement)
_ulauncher_rpm=$(echo "${_ulauncher_rpm_url}" | cut -d "/" -f 9)

if ! [[ -f "$(command -v wget)" ]]; then
  exit 1
fi

echo "Downloading Ulauncher rpm..."
wget -q --show-progress "${_ulauncher_rpm_url}"

echo "Installing Ulauncher..."
sudo dnf install -y -q "$(pwd)/${_ulauncher_rpm}"

echo "Cleaning up rpm..."
rm -f "$(pwd)/${_ulauncher_rpm}"

echo "Done!"

