#!/usr/bin/env bash

if ! type flatpak >/dev/null 2>&1; then
    exit 0
fi

echo ""
echo "======================================"
echo "= Installing Flatpak Packages         ="
echo "======================================"
echo ""

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

declare FLATPAK_PACKAGES=(
    com.github.miguelmota.Cointop
    com.discordapp.Discord
    org.telegram.desktop
    im.slack.Slack
    com.github.mdh34.quickdocs
    org.fedoraproject.MediaWriter
    net.ankiweb.Anki
    org.zealdocs.Zeal
    org.wireshark.Wireshark
    com.getpostman.Postman
    com.bitwarden.desktop
    com.github.micahflee.torbrowser-launcher
)

echo "${FLATPAK_PACKAGES[@]}"
echo ""

flatpak install -y "${FLATPAK_PACKAGES[@]}"
