#!/usr/bin/env bash

# lifted from https://github.com/MunifTanjim/scripts.bash

_xdg_bin_dir="${HOME}/.local/bin"

if ! [[ -d "${_xdg_bin_dir}" ]]; then
  mkdir -p "${_xdg_bin_dir}"
fi

curl -fsSL https://starship.rs/install.sh | bash -s -- --bin-dir "${_xdg_bin_dir}" --yes

echo "Setting up binary: starship"
if test "$(readlink --canonicalize-existing --no-newline /usr/local/bin/starship)" != "${_xdg_bin_dir}/starship"; then
  sudo ln -nsf "${_xdg_bin_dir}/starship" /usr/local/bin/starship
fi
