#!/usr/bin/env bash

set -euxo pipefail

function setup_rpmfusion() {
    sudo dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-32.noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-32.noarch.rpm
}

function setup_copr() {
    sudo dnf copr enable dawid/better_fonts
    sudo dnf copr enable szydell/system76
}

declare RPM_PACKAGES=(
    zsh '@c-development' '@development-tools' '@container-management'
    nano tmux xsel cargo npm jq ShellCheck toolbox
    python3-devel python3-pip gnome-tweak-tool chrome-gnome-shell 
    p7zip p7zip-plugins ffmpeg-libs lsof akmod-nvidia most
    fontconfig-enhanced-defaults fontconfig-font-replacements
    system76-dkms system76-power system76-driver system76-firmware
    firmware-manager system76-io-dkms ansible tor torsocks
    proxychains neofetch htop lynis ulauncher snapper systemd-swap
    util-linux-user timeshift zram zram-generator zram-generator-defaults
)

echo "${RPM_PACKAGES[@]}"
echo ""

setup_rpmfusion
setup_copr
sudo dnf install -y "${RPM_PACKAGES[@]}"

echo "Post installation setup..."
sudo systemctl enable system76-power system76-power-wake system76-firmware-daemon
systemctl enable --user com.system76.FirmwareManager.Notify.timer
echo "Done!"
