#!/usr/bin/env bash

set -euo pipefail

echo "Adding VSCode GPG key..."
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc

echo "Adding RPM Repository..."
sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

echo "Install VSCode..."
sudo dnf install -y code

echo "Done!"
