#!/usr/bin/env bash

# lifted from https://github.com/MunifTanjim/scripts.bash

echo "Downloading Keybase package: keybase_amd64.deb"
curl --progress-bar -O https://prerelease.keybase.io/keybase_amd64.deb
# if you see an error about missing `libappindicator1`
# from the next command, you can ignore it, as the
# subsequent command corrects it
echo "Installing Keybase package..."
sudo dpkg -i keybase_amd64.deb
echo "Resolving dependencies..."
sudo apt install -f -y
echo "Done! Running Keybase..."
run_keybase
rm -f keybase_amd64.deb